baseURL = "https://blog.sekixu.dev/"
languageCode = "zh-tw"
title = "SekiXu Dev Note"
theme = "hugo-theme-stack"

[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullContent = true

[params.footer]
since = 2023

[params.dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02"

[params.sidebar]
compact = false
emoji = "ğŸ“­"
subtitle = "Seki ã§ã™ã€ã‚¦ã‚§ãƒ–ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã‚’ã‚„ã¦ã„ã¾ã™ã€‚"

[params.sidebar.avatar]
enabled = true
local = true
src = "images/avatar.png"

[params.article]
readingTime = true

[params.comments]
enabled = true
provider = "gitalk"

[params.comments.gitalk]
owner = "antony0016"
admin = ["antony0016"]
repo = "https://github.com/antony0016/sekixu-blog-comment"
clientID = "c847fb4dab9e4beb6911"
clientSecret = "8e748c10584b376b8b5cea80d16c6ecb932ed2e4"

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "categories"
[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"
[params.widgets.homepage.params]
limit = 10

[colorScheme]
toggle = true
default = "light"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/antony0016/"
[menu.social.params]
icon = "brand-github"
